PUBLIC CLASS HELLOWORLD{
	PUBLIC STATIC VOID MAIN(STRING[] ARGS){ //THIS IS THE SKELETON OF ANY JAVA PROGRAM
		SYSTEM.OUT.PRINTLN("HELLO WORLD!"); //SYSTEM IS A CLASS, OUT IS AN OBJECT IN THAT CLASS, PRINTLN IS A METHOD
		//JRE IS A RUNTIME ENVIRONMENT, THAT ALLOWS YOU TO RUN COMPILED PROGRAMS. JDK ALLOWS YOU TO COMPILE A .JAVA FILE, MAKING IT INTO BYTECODE.
	}
}
